### ISSUE TITLE
Problem with example_input 

### ISSUE THREAD

**Issue by ZachNikolakis** [Tagliacollo/PFinderUCE-SWSC-EN#1]
I am trying to run the example data but I keep getting this error -
Traceback (most recent call last):
  File "py_script/SWSCEN.py", line 25, in <module>
    process_dataset_metrics(dataset_path, ['entropy'], minimum_window_size = 50, outfilename = '%s.csv' % (name))
  File "/work/zach/PFinderUCE-SWSC-EN-master/py_script/functions_metrics.py", line 38, in process_dataset_metrics
    aln = AlignIO.read(open(dataset_path), "nexus")
IOError: [Errno 2] No such file or directory: 'example_input/example_dataset.nex'
I am in the PFinderUCE-SWSC-EN-master directory and the command I am running is 
python py_script/SWSCEN.py example_input/example_dataset.nex Test

Thanks,
Zach

**Comment by roblanf** [comment]
Hi Zach,

Thanks for the bug report. Turns out this is a simple one - you just need to provide the full file path to your input file, something like this:

```
python py_script/SWSCEN.py ~/Downloads/PFinderUCE-SWSC-EN-master/example_input/example_dataset.nex Test
```

An easy way to do this is to first type:

```
python py_script/SWSCEN.py
```

then just drag and drop your input file onto the terminal (if you're on a mac).

I'll update the README to make this clear.

Cheers,

Rob

**Comment by roblanf** [comment]
Readme is updated. Note that you should also provide a full filepath to your output directory, otherwise it will likely end up in your root directory.
